#include "da_test.h"

#include "io.h"
#include "rom.h"
#include "tools/da/da.h"
#include "util.h"

#include <check.h>

#include <ftw.h>
#include <libgen.h>
#include <stdlib.h>
#include <unistd.h>

static const char nes_test_roms_path[] = "src/unittest/input/roms/nes-test-roms/";
static const char nes_test_roms_ref_path[] = "src/unittest/reference/da/nes-test-roms/";

static int disassemble_rom(const char *rom_filename, const struct stat *sb, int type_flag)
{
  (void)sb;

  if (type_flag != FTW_F || !nn_ends_with(rom_filename, ".nes"))
  {
    return 0; /* continue iteration */
  }

  /* Open the ROM file. */
  unsigned char *rom_data = NULL;
  size_t rom_size = 0;
  if (read_all(rom_filename, &rom_data, &rom_size) == -1)
  {
    quit_strerror("Could not open the given ROM file '%s' for reading", rom_filename);
  }

  struct RomHeader header = rom_make_header(rom_data);
  uint8_t *prg_data;
  size_t prg_data_size;
  rom_prg_data(&header, rom_data, &prg_data, &prg_data_size);

  /* Calculate the filename of the reference file, relative to the path of the
   * ROMS. */
  char *ref_filename =
      nn_strcat(nes_test_roms_ref_path, rom_filename + sizeof(nes_test_roms_path) - 1);
  memcpy(ref_filename + strlen(ref_filename) - 4, ".ref", 4);

  /* Calculate the reference file path. */
  char *ref_path = nn_dirname(ref_filename);

  /* In case the reference file does not exist, create it. We just disassemble
   * the ROM to the reference file, and assume it is valid. */
  FILE *ref_fp;
  if (access(ref_filename, F_OK) < 0)
  {
    /* In case the reference path does not exist, create it. */
    if (access(ref_path, F_OK) < 0 &&
        nn_mkdirs(ref_path, S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH) < 0)
    {
      quit_strerror("Could not create reference directory '%s'", ref_path);
    }

    /* Create the reference file. */
    if ((ref_fp = fopen(ref_filename, "w")) == NULL)
    {
      quit_strerror("Could not open reference file '%s' for writing", ref_filename);
    }

    /* Write assembly to the reference file. */
    da_disassemble(ref_fp, prg_data, prg_data_size);
  }
  else
  {
    /* A reference file exists, compare it with the assembly generated by
     * da_disassemble(). */
    if ((ref_fp = fopen(ref_filename, "r")) == NULL)
    {
      quit_strerror("Could not open reference file '%s' for reading", ref_filename);
    }

    /* Disassemble the ROM in memory. */
    char *buffer;
    size_t buffer_size;
    FILE *fp = open_memstream(&buffer, &buffer_size);
    da_disassemble(fp, prg_data, prg_data_size);
    rewind(fp);

    /* Compare the assembly, print out the first line that differs. */
    unsigned MAX_LINE = 30;
    unsigned line_number = 0;
    char line[MAX_LINE];
    char ref_line[MAX_LINE];
    while (fgets(line, sizeof line, fp) && fgets(ref_line, sizeof ref_line, ref_fp) &&
           strncmp(line, ref_line, MAX_LINE) == 0)
    {
      ++line_number;
    }

    ck_assert_msg(strncmp(line, ref_line, MAX_LINE) == 0,
                  "Found a difference on line %d:\n"
                  "\tassembly:           %s"
                  "\treference assembly: %s",
                  line_number, line, ref_line);

    fclose(fp);
    free(buffer);
  }

  fclose(ref_fp);
  free(rom_data);
  free(ref_path);
  free(ref_filename);

  return 0;
}

START_TEST(test_disassemble_test_roms)
{
  ftw(nes_test_roms_path, disassemble_rom, 10);
}
END_TEST

TCase *make_da_test_case(void)
{
  TCase *tc = tcase_create("Disassembler test cases");
  tcase_add_test(tc, test_disassemble_test_roms);
  return tc;
}
